/**
 * Represents the structure of a repository as returned by the GitHub REST API.
 * This interface captures the metadata needed to display and filter repositories.
 */
export interface GitHubRepo {
	/** The name of the repository */
	name: string;
	/** The description of the repository, or null if not provided */
	description: string | null;
	/** The primary programming language of the repository, or null */
	language: string | null;
	/** The number of stars (stargazers) the repository has received */
	stargazers_count: number;
	/** The number of forks of this repository */
	forks_count: number;
	/** List of topics/tags assigned to the repository */
	topics: string[];
	/** The direct URL to the GitHub repository page */
	html_url: string;
	/** The URL of the homepage/website associated with the repository, or null */
	homepage: string | null;
	/** Whether the repository is private */
	private: boolean;
	/** Whether the repository is a fork of another repository */
	fork: boolean;
	/** Whether the repository has been archived */
	archived: boolean;
	/** ISO 8601 timestamp representing when the repository was last updated */
	updated_at: string;
	/** ISO 8601 timestamp representing when the repository was created */
	created_at: string;
}

/**
 * Custom overrides defined by the user to customize how a project appears in the portfolio.
 * Every field is optional to allow selective overrides of GitHub-provided metadata.
 */
export interface ProjectOverride {
	/** Whether the project should be highlighted/featured on the portfolio */
	featured?: boolean;
	/** A sorting weight or index to determine the order of the project in lists */
	order?: number;
	/** A short, engaging tagline to display alongside or instead of the description */
	tagline?: string;
	/** A custom markdown or plain text description to override the GitHub repository description */
	description?: string;
	/** A custom live demo URL if different from the GitHub repository homepage */
	demoUrl?: string;
	/** Whether to hide this repository completely from the portfolio */
	hide?: boolean;
	/** Whether to show this repository even if it is a fork (useful if global settings exclude forks) */
	showFork?: boolean;
}

/**
 * Represents the structure of the system's configuration file (e.g., portfolio.config.json).
 * This defines global settings and individual repository overrides.
 */
export interface PortfolioConfig {
	/** Global synchronization and display settings */
	settings: {
		/** Whether to show repository forks globally by default */
		showForks: boolean;
		/** Whether to show archived repositories */
		showArchived: boolean;
		/** A list of repository names to completely exclude from the portfolio */
		excludeRepos: string[];
	};
	/** A map of repository names to their custom overrides */
	projects: Record<string, ProjectOverride>;
}

/**
 * Represents the final, fully-resolved project structure consumed by the UI.
 * This is generated by merging GitHub repository data with user-defined configuration overrides,
 * processing repository language statistics, and fetching the repository's README.
 */
export interface Project {
	/** The name of the project/repository */
	name: string;
	/** A URL-friendly slug generated from the project name */
	slug: string;
	/** A short, engaging tagline for the project, or null */
	tagline: string | null;
	/** The detailed description of the project, or null */
	description: string | null;
	/** The primary language used in the project, or null */
	language: string | null;
	/** A breakdown of languages used in the repository, mapped to their byte counts */
	languages: Record<string, number>;
	/** The number of GitHub stars the project has */
	stars: number;
	/** The number of GitHub forks the project has */
	forks: number;
	/** List of topics/tags assigned to the project */
	topics: string[];
	/** The URL to the GitHub repository */
	url: string;
	/** The URL to the live demo, or null if none is available */
	demoUrl: string | null;
	/** Whether the repository is private */
	isPrivate: boolean;
	/** Whether the repository is a fork */
	isFork: boolean;
	/** Whether the project should be highlighted/featured in the UI */
	featured: boolean;
	/** An optional sorting weight to control UI display order, or null */
	order: number | null;
	/** ISO 8601 timestamp representing when the project was last updated */
	updatedAt: string;
	/** ISO 8601 timestamp representing when the project was created */
	createdAt: string;
	/** The markdown body from portfolio.md (or README.md fallback), or null */
	portfolioContent: string | null;
	/** Tech stack used in the project, parsed from portfolio.md frontmatter */
	stack: string[];
	/** Key highlights/accomplishments, parsed from portfolio.md frontmatter */
	highlights: string[];
	/** The developer's role in the project, parsed from portfolio.md frontmatter */
	role: string | null;
	/** Project status (e.g., "active", "completed", "archived"), parsed from portfolio.md frontmatter */
	status: string | null;
}

/** Parsed YAML frontmatter from a repo's portfolio.md file */
export interface PortfolioFrontmatter {
	tagline?: string;
	role?: string;
	status?: string;
	stack?: string[];
	highlights?: string[];
	description?: string;
}

